server:
  port: 8091
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_product
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update