server:
  port: 8093
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_shopping
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/