server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          url:
          searchPath: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: