server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lisandrofunes/microservicios.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user: 
      name: root
      password: s3cr3t