server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/lisandrofunes/microservicios.git
          searchPath: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user: root
      name: s3cr3t